### ISSUE TITLE
Query result issue

### ISSUE THREAD

**Issue by nikotincheg** [influxdb/influxdb-java#101]
I use Influxdb v0.9.4. 

I have measurement 'test' with several fields in 'mydb' database.
I execute following code:

Query query = new Query("select * from test", "mydb");
QueryResult queryResult = influxDB.query(query);
QueryResult.Result result1 = queryResult.getResults().get(0);
List<QueryResult.Series> seriesList = result1.getSeries();
QueryResult.Series series1 = seriesList.get(0);
String name = series1.getName(); // filled
Map<String, String> tagsMap = series1.getTags(); // is null, but I have 3 tags in 'test'
List<String> columnNameList = series1.getColumns(); // filled with all columns names included tags: size = 10
List<List<Object>> list = series1.getValues(); // filled with correct number of List<Object>. size = count of lines in 'test' measurement (select * from test)
Object firstFieldValue = list.get(0); // is ArrayList with size = columnNameList.size
String className = ((ArrayList) firstFieldValue).get(0).getClass().getName(); // = 'java.lang.Object' - can't be used as value

How get the fields values and tags

**Comment by Kindrat** [comment]
0.9.3 version removed implicit group by *. You need to add it yourself to your queries, if you want to see tags. Ref: InfluxDBTest.testWrite

**Comment by nikotincheg** [comment]
Kindrat, thanks you for your help. It works to get tagsMap (with names and values), but I can't get fields values all the same((...I think it's influxdb response deserializing issue...

**Comment by Kindrat** [comment]
Yep, that is not best part of client lib. I suggest writing own parser. Something like:
int columnIndex = getIndexByName(columns, "replicaN")
int replicaNValue = int.class.cast(values.get(0).get(columnIndex));

You know types of all values and can cast from Object. It could be something generic, that will receive list of values, column name and type.

**Comment by nikotincheg** [comment]
I can't cast it to my type becaues all values have 'java.lang.Object' type and following code:

float.class.cast(values.get(0).get(columnIndex)) 

returns next exeption: "java.lang.ClassCastException: Cannot cast java.lang.Object to float". Where my value has float type in InfluxDB, the same with String type and any other...

As result I can write data to InfluxDB but can't read it((....

**Comment by Kindrat** [comment]
Did you try objects Float, Integer, etc.? Could you post your db init code and simple test with some of your points?
InfluxDBTest.testWrite returns list of three doubles in values, not just generic objects.

**Comment by nikotincheg** [comment]
Kindrat - thanks for your help! I found the problem. In my project old "com.google.code.gson" version is used. I updated it to 2.3.1 and it works!
