### ISSUE TITLE
pom.xml is not able to recognize 2.0 version and getting null pointer except in TimeUtil.java

### ISSUE THREAD

**Issue by gargde** [influxdb/influxdb-java#109]
I am using below dependency for influx db java connector but pom.xml couldn't find it.
<dependency>
			<groupId>org.influxdb</groupId>
			<artifactId>influxdb-java</artifactId>
			<version>2.0</version>
</dependency>

then I try to take the source code and compile it locally and generated influxdb-java-2.0-SNAPSHOT.jar but this is giving the null pointer exception which I believe already resolved in https://github.com/influxdb/influxdb-java/issues/63 but some how it is not available in the head. 

Can you please help how to resolve this ?

Exception in thread "main" java.lang.NullPointerException
	at org.influxdb.impl.TimeUtil.toTimePrecision(TimeUtil.java:21)
	at org.influxdb.impl.InfluxDBImpl.write(InfluxDBImpl.java:155)
	at com.relcy.analytics.influxdb.InfluxDbHelper.insertUserMetrics(InfluxDbHelper.java:55)
	at com.relcy.analytics.kafka.consumer.SystemUserAnalyticsConsumer$4.call(SystemUserAnalyticsConsumer.java:95)
	at com.relcy.analytics.kafka.consumer.SystemUserAnalyticsConsumer$4.call(SystemUserAnalyticsConsumer.java:1)

**Comment by Kindrat** [comment]
2.0 is not published
http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.influxdb%22%20AND%20a%3A%22influxdb-java%22

**Comment by gargde** [comment]
How do I workaround the null pointer exception ?

**Comment by gargde** [comment]
@majst01 any suggestion ? I am bit stuck at this point.

**Comment by majst01** [comment]
Hi,

you are not using the latest version, try to clone this repo and build it in you environment.
Publishing to maven is currently going further.

**Comment by gargde** [comment]
Thanks @majst01. with the latest build null pointer exception is gone and I see below logs in influx db log file. 

[wal] 2015/10/27 00:32:06 WAL writing to /var/opt/influxdb/wal/metric/default/165
[http] 2015/10/27 00:32:06 172.31.10.215 - admin [27/Oct/2015:00:32:06 +0000] POST /write?consistency=all&db=metric&p=%5BREDACTED%5D&precision=ms&rp=default&u=admin HTTP/1.1 204 0 - okhttp/2.4.0 2694ee30-7c42-11e5-81b0-000000000000 12.838617ms
[wal] 2015/10/27 00:32:11 Flush due to idle. Flushing 492 series with 492 points and 30081 bytes from partition 1
[wal] 2015/10/27 00:32:11 write to index of partition 1 took 55.341207ms
[wal] 2015/10/27 00:32:12 Flush due to idle. Flushing 1 series with 1 points and 56 bytes from partition 1
[wal] 2015/10/27 00:32:12 write to index of partition 1 took 3.990452ms
[wal] 2015/10/27 00:32:18 Flushing 1 measurements and 1 series to index
[wal] 2015/10/27 00:32:18 Metadata flush took 1.222764ms
[wal] 2015/10/27 00:32:20 Flushing 1 measurements and 1 series to index
[wal] 2015/10/27 00:32:20 Metadata flush took 1.329047ms
[wal] 2015/10/27 00:32:21 Flush due to idle. Flushing 495 series with 495 points and 30258 bytes from partition 1
[wal] 2015/10/27 00:32:21 write to index of partition 1 took 60.292042ms
[wal] 2015/10/27 00:32:26 Flushing 1 measurements and 1 series to index
[wal] 2015/10/27 00:32:26 Metadata flush took 1.304345ms
[wal] 2015/10/27 00:32:31 Flush due to idle. Flushing 495 series with 495 points and 30276 bytes from partition 1
[wal] 2015/10/27 00:32:31 write to index of partition 1 took 62.045692ms
[wal] 2015/10/27 00:32:41 Flush due to idle. Flushing 495 series with 495 points and 30285 bytes from partition 1
[wal] 2015/10/27 00:32:41 write to index of partition 1 took 59.612456ms
[wal] 2015/10/27 00:32:51 Flush due to idle. Flushing 495 series with 495 points and 30285 bytes from partition 1
[wal] 2015/10/27 00:32:51 write to index of partition 1 took 79.522433ms
[wal] 2015/10/27 00:32:58 Flushing 1 measurements and 1 series to index
[wal] 2015/10/27 00:32:58 Metadata flush took 1.430121ms
[wal] 2015/10/27 00:33:01 Flush due to idle. Flushing 495 series with 495 points and 30285 bytes from partition 1
[wal] 2015/10/27 00:33:01 write to index of partition 1 took 66.396521ms
[wal] 2015/10/27 00:33:02 Flushing 1 measurements and 1 series to index
[wal] 2015/10/27 00:33:02 Metadata flush took 1.228731ms

how ever I don't see any data is being persisted on influx db. I am quite puzzled now. any thoughts would help.
