### ISSUE TITLE
udp port is not opening after influxdb restart

### ISSUE THREAD

**Issue by kicketster** [influxdb/influxdb-java#114]
[[udp]]
  enabled = true
  bind-address = ":8089"
  database = "foo"
  batch-size = 1000
  batch-timeout = "1s"
  batch-pending = 5

I did this as in instruction in the config file and restarted influxdb service. 
But when I check the ports with netstat, I found out the port is still not open even though the other http type ports (8086, 8088) are open. 

Any solution?

**Comment by majst01** [comment]
Hi,

this is related to influxdb and not influxdb-java the java driver for the influxdb database. Did you check 

https://influxdb.com/docs/v0.9/write_protocols/udp.html

and how did you check that udp is not open ?

try 
netstat -ulp

Greetings
