### ISSUE TITLE
is support async？

### ISSUE THREAD

**Issue by rfyiamcool** [influxdb/influxdb-java#19]
is support async？

**Comment by majst01** [comment]
I guess you want async support for write, right ?

This is not implemented. But should be quite easy with resteasy which drives the communication to influxdb. Feel free to send a pull request.

**Comment by majst01** [comment]
I plan to make the write available in a async flavour in the 0.9.0_support branch.

**Comment by majst01** [comment]
the actual version 2.0-SNAPSHOT has batch support built in, so i close this issue.
