### ISSUE TITLE
mvn 2

### ISSUE THREAD

**Issue by tecbea** [influxdb/influxdb-java#25]
Hi,
cant the influxdb client be compatible with mvn2 ?

mvn2 build is used yet in a lot of software ...

**Comment by majst01** [comment]
Hi,

according to: http://maven.apache.org/maven-2.x-eol.html 
Maven 2 is EOL since 2014, last release was 2009 !

Therefore i think there is no need to support this ancient version. 

Greetings

**Comment by damnhandy** [comment]
-1

Agree with @majst01 it is close to asking for Java 1.5 compatibility. Are you looking to build form sources with Maven 2, or simply use it as part of a Maven 2 build process?

**Comment by majst01** [comment]
Ok so i close this ticket.
