### ISSUE TITLE
Data is written with delay

### ISSUE THREAD

**Issue by albours** [influxdb/influxdb-java#28]
When I repeatedly write to the influxdb without interval, with the following code:

	public void write_fastWrite2_unknow()
	{
		m_log.debug("==================== START TEST: write_fastWrite2_unknow");
		
		CInfluxDriver drv = new CInfluxDriver(m_prop);
		
		String tag = "new1";
		
		for (int i=0; i<5; i++)
		{
			CTag ctag = new CTag(tag, new CValue(i, CState.GOOD, Calendar.getInstance().getTime()));
			boolean result = drv.write(ctag);
			m_log.debug("Write ctag: "+ctag.toString());
			m_log.debug("CTag time of long: "+ctag.getValues().get(0).getTimestamp().getTime());
			assertTrue("Failed to write ctag!", result);
			
			
			try { Thread.sleep(250); } 
			catch (InterruptedException e) { m_log.error("Failed sleep. "+e.toString()); }
			
		}
	}

I have the following contents in the influxdb series:
![Result write](https://pp.vk.me/c622818/v622818056/2086f/OLAx3UCedvc.jpg)

And also the following log:
> 19:36:03,181 DEBUG TestCInfluxDriver:write_fastWrite2_unknow:362 - ==================== START TEST: write_fastWrite2_unknow
> 19:36:04,061  INFO CInfluxDriver:connect:87 - Done connection to InfluxDB.
> 19:36:04,153 DEBUG TestCInfluxDriver:write_fastWrite2_unknow:372 - Write ctag: Item: new1 Value: [Value: 0 Type: java.lang.Integer Timestamp: 18/03/2015 > 19:36:03 State: GOOD Param: null]
> 19:36:04,153 DEBUG TestCInfluxDriver:write_fastWrite2_unknow:373 - CTag time of long: 1426692963231

> 19:36:04,468 DEBUG TestCInfluxDriver:write_fastWrite2_unknow:372 - Write ctag: Item: new1 Value: [Value: 1 Type: java.lang.Integer Timestamp: 18/03/2015 > 19:36:04 State: GOOD Param: null]
> 19:36:04,469 DEBUG TestCInfluxDriver:write_fastWrite2_unknow:373 - CTag time of long: 1426692964403
> 19:36:04,768 DEBUG CInfluxDriver:write:530 - ____[1] Serie row: {time_last=1.426692963231E12, sequence_number=1.697800001E9, time=1.426692963231E12, value=0.0}

> 19:36:04,774 DEBUG TestCInfluxDriver:write_fastWrite2_unknow:372 - Write ctag: Item: new1 Value: [Value: 2 Type: java.lang.Integer Timestamp: 18/03/2015 > 19:36:04 State: GOOD Param: null]
> 19:36:04,777 DEBUG TestCInfluxDriver:write_fastWrite2_unknow:373 - CTag time of long: 1426692964719
> 19:36:05,076 DEBUG CInfluxDriver:write:530 - ____[1] Serie row: {time_last=1.426692964719E12, sequence_number=1.697800001E9, time=1.426692963231E12, value=0.0}

> 19:36:05,087 DEBUG TestCInfluxDriver:write_fastWrite2_unknow:372 - Write ctag: Item: new1 Value: [Value: 3 Type: java.lang.Integer Timestamp: 18/03/2015 > 19:36:05 State: GOOD Param: null]
> 19:36:05,087 DEBUG TestCInfluxDriver:write_fastWrite2_unknow:373 - CTag time of long: 1426692965028
> 19:36:05,378 DEBUG CInfluxDriver:write:530 - ____[1] Serie row: {time_last=1.426692964719E12, sequence_number=1.697800001E9, time=1.426692963231E12, value=0.0}

> 19:36:05,384 DEBUG TestCInfluxDriver:write_fastWrite2_unknow:372 - Write ctag: Item: new1 Value: [Value: 4 Type: java.lang.Integer Timestamp: 18/03/2015 > 19:36:05 State: GOOD Param: null]
> 19:36:05,385 DEBUG TestCInfluxDriver:write_fastWrite2_unknow:373 - CTag time of long: 1426692965338

Although I expect the following result:
![Result write 2](https://pp.vk.me/c625325/v625325056/2836a/nYG7eZKGinM.jpg)

With the following log:
> 19:59:02,746 DEBUG TestCInfluxDriver:write_fastWrite2_unknow:362 - ==================== START TEST: write_fastWrite2_unknow
> 19:59:04,330  INFO CInfluxDriver:connect:87 - Done connection to InfluxDB.
> 19:59:04,472 DEBUG TestCInfluxDriver:write_fastWrite2_unknow:372 - Write ctag: Item: new1 Value: [Value: 0 Type: java.lang.Integer Timestamp: 18/03/2015 > 19:59:02 State: GOOD Param: null]
> 19:59:04,472 DEBUG TestCInfluxDriver:write_fastWrite2_unknow:373 - CTag time of long: 1426694342848
> 19:59:06,062 DEBUG CInfluxDriver:write:530 - ____[1] Serie row: {time_last=1.426694342848E12, sequence_number=1.697870001E9, time=1.426694342848E12, value=0.0}

> 19:59:06,070 DEBUG TestCInfluxDriver:write_fastWrite2_unknow:372 - Write ctag: Item: new1 Value: [Value: 1 Type: java.lang.Integer Timestamp: 18/03/2015 > 19:59:05 State: GOOD Param: null]
> 19:59:06,070 DEBUG TestCInfluxDriver:write_fastWrite2_unknow:373 - CTag time of long: 1426694345973
> 19:59:07,696 DEBUG CInfluxDriver:write:530 - ____[1] Serie row: {time_last=1.426694345973E12, sequence_number=1.697880001E9, time=1.426694345973E12, value=1.0}
> 19:59:07,702 DEBUG CInfluxDriver:write:530 - ____[2] Serie row: {time_last=1.426694345973E12, sequence_number=1.697870001E9, time=1.426694342848E12, value=0.0}

> 19:59:07,709 DEBUG TestCInfluxDriver:write_fastWrite2_unknow:372 - Write ctag: Item: new1 Value: [Value: 2 Type: java.lang.Integer Timestamp: 18/03/2015 > 19:59:07 State: GOOD Param: null]
> 19:59:07,709 DEBUG TestCInfluxDriver:write_fastWrite2_unknow:373 - CTag time of long: 1426694347571
> 19:59:09,263 DEBUG CInfluxDriver:write:530 - ____[1] Serie row: {time_last=1.426694347571E12, sequence_number=1.697890001E9, time=1.426694347571E12, value=2.0}
> 19:59:09,264 DEBUG CInfluxDriver:write:530 - ____[2] Serie row: {time_last=1.426694347571E12, sequence_number=1.697880001E9, time=1.426694345973E12, value=1.0}
> 19:59:09,264 DEBUG CInfluxDriver:write:530 - ____[3] Serie row: {time_last=1.426694345973E12, sequence_number=1.697870001E9, time=1.426694342848E12, value=0.0}

> 19:59:09,274 DEBUG TestCInfluxDriver:write_fastWrite2_unknow:372 - Write ctag: Item: new1 Value: [Value: 3 Type: java.lang.Integer Timestamp: 18/03/2015 > 19:59:09 State: GOOD Param: null]
> 19:59:09,274 DEBUG TestCInfluxDriver:write_fastWrite2_unknow:373 - CTag time of long: 1426694349209
> 19:59:10,897 DEBUG CInfluxDriver:write:530 - ____[1] Serie row: {time_last=1.426694349209E12, sequence_number=1.697900001E9, time=1.426694349209E12, value=3.0}
> 19:59:10,898 DEBUG CInfluxDriver:write:530 - ____[2] Serie row: {time_last=1.426694349209E12, sequence_number=1.697890001E9, time=1.426694347571E12, value=2.0}
> 19:59:10,898 DEBUG CInfluxDriver:write:530 - ____[3] Serie row: {time_last=1.426694347571E12, sequence_number=1.697880001E9, time=1.426694345973E12, value=1.0}
> 19:59:10,898 DEBUG CInfluxDriver:write:530 - ____[4] Serie row: {time_last=1.426694345973E12, sequence_number=1.697870001E9, time=1.426694342848E12, value=0.0}

> 19:59:10,908 DEBUG TestCInfluxDriver:write_fastWrite2_unknow:372 - Write ctag: Item: new1 Value: [Value: 4 Type: java.lang.Integer Timestamp: 18/03/2015 > 19:59:10 State: GOOD Param: null]
> 19:59:10,909 DEBUG TestCInfluxDriver:write_fastWrite2_unknow:373 - CTag time of long: 1426694350774

Such scenario happens if to change a write interval from 250 ms to 1500 ms.

		{
			//...
			try { Thread.sleep(1500); } 
			catch (InterruptedException e) { m_log.error("Failed sleep. "+e.toString()); }
			//...
		}

Data in a series represent structure of the list quickly to address to the following record (by means of a field time_last).
Mattering time of a certain record, it is possible to receive previous, by means of request a 'select * from new1 where time<1426694347571000000 limit 2', but it is impossible to receive the following record after the current.

The procedure WRITE before write data, running multiple queries, the elapsed time does not exceed 60-120 ms.

##### Please tell me why there are such strange events, when the interval between records in the influxdb is very small?

**Comment by albours** [comment]
P. S. In the first case (where the intervals between the small writting) after writing the data, I request a list of all the rows in the series and receive only one line (although would receive two, three, four or more), it can be seen in the log.

**Comment by majst01** [comment]
Hi,

i dont know anything about CInfluxDriver ? Is this a wrapper around my influxdb java driver ? I cant tell what happens because i dont know how CInfluxDriver works.

Greetings
Stefan

**Comment by albours** [comment]
Yes indeed. This wrapper around your influxdb-java. I solved this problem, it on the computer on which installed influxdb, time lagged behind, from the time the computer that runs the java application.
Thus, the data writed in the future :smile:

**Comment by majst01** [comment]
So ntp is you friend.

may i close this ticket ?

**Comment by albours** [comment]
Yes, I already use ntp. Issue can be closed, thank you for attention.
