### ISSUE TITLE
Http Connection not getting closed ( CLOSE_WAIT)

### ISSUE THREAD

**Issue by harmanjassal** [influxdb/influxdb-java#29]
Recently we ran into an issue where influx db went down and client publishing metrics started using lot of file descriptors.

Upon debugging I found infludb java client is not closing connection if influx db host is not reachable.

lsof -a -p showed too many ipv4 connections in CLOSE_WAIT state. 

I think influx db client is not using connection pooling which is causing the issue.

**Comment by majst01** [comment]
Hi,

did you still encounter this problem ? I recommend to use the latest version of influxdb-java to get the newest http client implementation which might circumvent the issue you see. I will close this issue.
