### ISSUE TITLE
InfluxDB#describeContinuousQueries queries wrong endpoint resulting in 404 / Exception

### ISSUE THREAD

**Issue by btiernay** [influxdb/influxdb-java#30]
The following call:

```java
influxDb.describeContinuousQueries("events");
```

produces a call to:

```
http://localhost:8086/db/events/continuous_queries?u=root&p=root
```

Which results in a `404` and related exception. 

However, the admin interface generates:

```
http://localhost:8086/cluster/configuration?u=root&p=root
```

which produces the expected response. The implementation should be updated point to the correct endpoint.

**Comment by majst01** [comment]
As this is regarding the end of life influxdb 0.8x compatible version i will close this issue.

**Comment by btiernay** [comment]
I can't see how this is possible in the 0.9 branch as well. Should we reopen this ticket?

**Comment by btiernay** [comment]
Nvm, just saw `SHOW CONTINUOUS QUERIES` is now supported
