### ISSUE TITLE
Pedantic: Can Serie be renamed to Series?

### ISSUE THREAD

**Issue by contentfree** [influxdb/influxdb-java#32]
"series" is both the singular and plural form of the word. I thought it was a typo in the examples until I looked into the library itself.

**Comment by majst01** [comment]
God catch, but i would not break the actual api in the influxdb-0.8 compatible client library.
I slowly prepare a influxdb-0.9 compatible version which breaks api anyway and there i will rename serie -> series.

Greetings

**Comment by contentfree** [comment]
Makes sense. Thanks!
