### ISSUE TITLE
version 2.0 isn't published yet?

### ISSUE THREAD

**Issue by jhorwit2** [influxdb/influxdb-java#37]
Do you plan to publish version 2.0 soon? The maven tag you have in the README doesn't work :(

**Comment by majst01** [comment]
Hi,

As im actually off wifi for a week or so, so please be patient.

**Comment by jhorwit2** [comment]
Sounds good.



On Jun 21, 2015, at 6:24 PM, Stefan Majer <notifications@github.com> wrote:

Hi,

As im actually off wifi for a week or so, so please be patient.

—
Reply to this email directly or view it on GitHub
<https://github.com/influxdb/influxdb-java/issues/37#issuecomment-113964797>
.

**Comment by andremann** [comment]
I tried to install the artifact locally.
However, when I run the command  `$ mvn clean install -DskipTests=true`
it complains about a `com.sun.tools.javac.code.Symbol$CompletionFailure: class file for java.util.Optional not found`

Compiled with Java(TM) SE Runtime Environment (build 1.7.0_80-b15) and Apache Maven 3.0.5

**Comment by majst01** [comment]
Hi Andre,

I have no Idea why because in the whole code i do not use any java.util.Optional

git grep Optional .
src/main/java/org/influxdb/dto/BatchPoints.java: * {Other Notes Relating to This Type (Optional)}
src/main/java/org/influxdb/dto/QueryResult.java: * {Other Notes Relating to This Type (Optional)}

**Comment by andremann** [comment]
well.. strange.. :-/
However, as for a try, I deleted the test path and it installs the artifact.
I'm playing with it right now

**Comment by andremann** [comment]
BTW.. I get the error with or without skipping tests.
I also make a colleague of mine clone and compile on a different workstation.. 
still no luck, still the same error.

**Comment by majst01** [comment]
Ok i am compiling with java 8 and maven 3.3 would you please give it a try ? If this works i have to check why compiling with java 7 does not work.

**Comment by majst01** [comment]
Hi,

it was my fault, i added assertj in the java8 flavour instead the java7 flavour. Please pull the latest version and give it a try again.

Greetings
Stefan

**Comment by andremann** [comment]
It works fine now!
Thanks

**Comment by majst01** [comment]
fine

**Comment by ajsquared** [comment]
When do you think version 2.0 will be published?

Thanks for getting this client ready for 0.9!

**Comment by iziang** [comment]
when will version 2.0 be published?

Thanks!

**Comment by menchauser** [comment]
Hi. I'm waiting for the 2.0 version published too :-).

**Comment by amondnet** [comment]
https://jitpack.io/#influxdb/influxdb-java/influxdb-java-2.0
How about this?

**Comment by majst01** [comment]
Hi @amondnet 

Thanks for this hint, i did not know about that service, great. This is a solution for all the impatient.
But i still want to get it published to official Maven repos. I am already in contact with the people from influx to get this job done. They are all busy it will take a few days more.

I will keep you all updated.
Thanks for all your patience.
Greetings
Stefan

**Comment by jpbetz** [comment]
26+ days to publish a jar to maven central? I'm starting to think this will never happen.

**Comment by jhorwit2** [comment]
I'd suggest also looking at line protocol versus json as it's the preferred method and not deprecated like JSON is. With line protocol there are some performance notes to remember, like sorting tags & escaping certain chars.

**Comment by tedyoung** [comment]
Any update on getting this into the Maven repo?

**Comment by mihaicostin** [comment]
Waiting for this as well, but until then I manage quite well with https://jitpack.io/ (with the HEAD, since the 2.0 github release was missing the option to get the tags from the result). 
BTW, thanks @amondnet for that :)

**Comment by jlyheden** [comment]
+1 for deploying 2.0 to maven central

**Comment by majst01** [comment]
I'm going for vacation for 3 weeks and will create a new maven groupid for influxdb-java, because it seems impossible to push it to the existing groupid's due to permission problems.

**Comment by adamotte** [comment]
Please update to 2.0

**Comment by isabelabel** [comment]
Something new?

**Comment by tomnis** [comment]
Hi, I am waiting for this as well

**Comment by harryshayne** [comment]
Please update to 2.0 too

**Comment by derTobsch** [comment]
we are waiting too and would be very happy if you could update to 2.0.
Thanks for the influxdb! :)

**Comment by svage** [comment]
Waiting for this, too. Please publish the nice work you're doing here to maven. :+1:

**Comment by hkrizek** [comment]
@majst01 Please can you give us some date when we can expect working version in maven repository?

**Comment by jhorwit2** [comment]
@pauldix - would you be able to help?

**Comment by pauldix** [comment]
I'm not sure what to do with this, but I think either @majst01 or @toddboom can help with this.

**Comment by jtmelton** [comment]
Upvoting this, as well as a new cut (maybe 2.1) with the last few months of commits.

**Comment by geekychris** [comment]
Is there an alternative java based package that someone can recommend?  I am not feeling that confident when I see how long people have been asking for 2.0 to be published.

**Comment by majst01** [comment]
The only solution i can see is to publish this under a different groupid because the influxdb maven credentials are gone. I tried to get these from the influxdb guys but this did not work.

So i try to register influxdb-java/influxdb-java at sonatype and publish a 2.1 Version there. The drawback is that all consuming projects need to update their maven reference to influxdb.
I will not change the package name though.

Any comments on this ?

**Comment by jtmelton** [comment]
This sounds reasonable to me. When you say contacting the influxdb folks didn't work, what does that mean? Did they respond or just refuse to push? Any idea who the maintainer of this repo is, ie. who has pushed the previous versions?

**Comment by majst01** [comment]
The problem is that previously one guy from influxdb publish my work under their sonatype account but he left the company and the keys are gone.

I just create a ticket at sonatype now to register influxdb-java as groupid. Will see how long this would take but i will keep all you informed.

**Comment by pauldix** [comment]
So far we've been enable to get the credentials for the previous ID. Someone else had done it for us over a year ago when this got created and we've unfortunately lost it.

@toddboom, can you take another crack at trying to get the credentials?

**Comment by prtrahul** [comment]
I am also waiting for version 2.0

**Comment by rossmcdonald** [comment]
Version 2.0 has now been published to Maven Central, so the dependency tag specified in the README should now be working. Please let me know if anyone has trouble accessing the latest version.

**Comment by ajsquared** [comment]
Thanks @rossmcdonald! I was able to use the latest version from Maven Central.
