### ISSUE TITLE
java.lang.RuntimeException: bad timestamp

### ISSUE THREAD

**Issue by tecbea** [influxdb/influxdb-java#38]
This code with the tag "host" it gives an error:

Exception in thread "main" java.lang.RuntimeException: bad timestamp
	at org.influxdb.impl.InfluxDBErrorHandler.handleError(InfluxDBErrorHandler.java:19)

	Point point1 = Point.measurement(metric)
							.time(time, TimeUnit.MILLISECONDS)
							.field("value", cnt)
								.tag("host", host)
								.tag("region", region)							
							.build();

If i just remote the tag("host", host), it works.

Influxdb 0.9
with java client 2.0-SNAPSHOT

**Comment by majst01** [comment]
Hi,

just wrote a small test for that:

´´´java
		String dbName = "ticket38_" + System.currentTimeMillis();
		this.influxDB.setLogLevel(LogLevel.FULL);
		this.influxDB.createDatabase(dbName);
		Point point1 = Point
				.measurement("metric")
				.time(System.currentTimeMillis(), TimeUnit.MILLISECONDS)
				.field("value", 5)
				.tag("host", "host")
				.tag("region", "region")
				.build();
		this.influxDB.write(dbName, "default", point1);
		this.influxDB.deleteDatabase(dbName);
´´´

And i can not reproduce it, can you please add the 
		this.influxDB.setLogLevel(LogLevel.FULL);
and show me 
- the output of the logs and what version of influxdb are you using

**Comment by majst01** [comment]
One note, is it possible that your value of the host tag includes a "-" or " " or any similar, not yet to known one of the characters which have to be escaped ?
because i do not escape tag values for the moment because for me its not clear at all how to.

**Comment by tecbea** [comment]
try a region with spaces, you will get the error

		Point point1 = Point.measurement("metric")
				.time(System.currentTimeMillis(), TimeUnit.MILLISECONDS)
				.field("value", 5)
				.tag("host", "host")
				.tag("region", "region with spaces")
				.build();

**Comment by haninaguib** [comment]
You should reopen this. 
Your sanitizing change (65c5281) only sanitizes the tag.value.
In my case I needed to sanitize the this.measurement as well as tag key/value and field key/values.
Also as well as replacing ' ' with '\\ ' I also had to replace commas (in my place I replaced them with underscores).
I will try to read up on influxdb and their wire protocol and see what the correct approach is.

**Comment by majst01** [comment]
I hopefully covered all the escape issues with this last commit ( 82d32cb )

So please test with your code an report back.
