### ISSUE TITLE
Precision goes wrong

### ISSUE THREAD

**Issue by flisky** [influxdb/influxdb-java#44]
1. `BatchPoints.time` didn't affect the `Point` with null time, so it goes with batchpoints' time precision and point with TimeUnit.NANOSECONDS, which is default.

2. Point's default precision is NANOSECONDS, however it goes with default value 'System.currentTimeMillis()', which precision is `ms`.
Actually, the test pass because we set `ms` precision on BatchPoints!

Two negatives make positive:-)

**Comment by flisky** [comment]
By the way, I'm on the head of master.

**Comment by majst01** [comment]
Hi,

thanks for pointing this out, should both be fixed in 33af0e9214d18 and e9b8d70e3a531

Greetings
Stefan

**Comment by flisky** [comment]
I'm afraid that e9b8d70e3a53192aa9e3210de99ae338fd05c2e4 does not totally work, since there is another API `BatchPoints.build().point(point)`.

**Comment by majst01** [comment]
Hi

i cant verify your Bug, added a test therefore: e36a1f17f0872578b5186a0210a3d081676eb02b 

Can you please show me the code where the problem occurs ?

**Comment by flisky** [comment]
Here is a testcase -
```java
point = Point.measurement("test").field("a", 1).build();
batchPoints = BatchPoints.database("db").time(1, TimeUnit.MILLISECONDS).build();
batchPoints = batchPoints.point(point);
assertThat(batchPoints.lineProtocol()).asString().isEqualTo("test a=1 1\n");
```

PS: how to make 'mvn test' automatically pick the test class endswith 'Tests'? Thanks!
PPS: you forget to modify the doc string from 40 to 44:)

**Comment by majst01** [comment]
According to:
https://github.com/influxdb/influxdb/blob/master/tsdb/README.md#timestamp

timestamp has to be given in nanoseconds !
So your given testcase is wrong.

mvn test picks all java classes with @Test Annotation and which are located in src/test.

**Comment by flisky** [comment]
```Some write APIs allow passing a lower precision. If the API supports a lower precision, the timestamp may also be an integer epoch in microseconds, milliseconds, seconds, minutes or hours.```

Please see the example of the section `Time format` in the official docs [reading_and_writing_data](http://influxdb.com/docs/v0.9/concepts/reading_and_writing_data.html)

Also, my`mvn test` doesn't pick the `.*Tests` class automatically. Do you know why? Thanks.

**Comment by majst01** [comment]
Ok,

I forgot to add the precision=n argument to be set always, because internally Point and BatchPoints time is always calculated to nanos.

should be fixed now also.

**Comment by flisky** [comment]
Okay, got it.

**Comment by flisky** [comment]
However, I think your fix is incomplete.

The BatchPoints.Builder has a series function with precision, such like `getPrecision`/`setPrecision`/`time`.
Because we make BatchPoints' time precision always in NANO, the `setPrecision` should be removed and `time` should be translated into NANO at least.

My 2 cents.

**Comment by majst01** [comment]
BatchPoints.Builder does not have set/getPrecision only  time(time, precision). 
BatchPoints#setPrecision is package private and therefore not visible from an API perspective.

If you still have concerns please show me a code example

**Comment by flisky** [comment]
So doesn't we need to update time method in BatchPoints.Builder? It sets the precision!

**Comment by majst01** [comment]
Please create a test which shows the BUG.

Time and precision are calculated in Point#lineprotocol

**Comment by flisky** [comment]
`BatchPoints.time(1, TimeUnit.SECONDS).build()` goes with the precision SECONDS.

**Comment by majst01** [comment]
This example will not compile !

**Comment by flisky** [comment]
The upper case with NANO precision result -
```java
point = Point.measurement("test").field("a", 1).build();
batchPoints = BatchPoints.database("db").time(1, TimeUnit.MILLISECONDS).build();
batchPoints = batchPoints.point(point);
assertThat(batchPoints.lineProtocol()).asString().isEqualTo("test a=1 1000000\n");
```
If you think this case is illegal, here is another one
```java
point = Point.measurement("test").field("a", 1).build();
batchPoints = BatchPoints.database("db").time(1, TimeUnit.MILLISECONDS).point(point).build();
assertThat(batchPoints.lineProtocol()).asString().isEqualTo("test a=1 1000000\n");
```

They're both compiled!

**Comment by majst01** [comment]
You where right, i fixed the last occurence.

I will probably remove the BatchPoints as public API altogether because this is to much noise in the API.

**Comment by flisky** [comment]
Thank you for the fix.

I think BatchPoints is very useful in the situation like storm real-time processing. We can batch insert the data without more latency.

**Comment by majst01** [comment]
I think i will remove all properties from the BatchPoints.Builder which are available in Points as time, precision and keep BatchPoints

**Comment by majst01** [comment]
OK,

time is removed from BatchPoints, as already seen in our discussion this was a misleading API design. 

see https://github.com/influxdb/influxdb-java/issues/45
