### ISSUE TITLE
Cast time column from java.lang.String to java.util.Date

### ISSUE THREAD

**Issue by thetcc** [influxdb/influxdb-java#49]
The time column of query result is String type, and the format is like:   
"2015-07-01T09:06:46.852663Z"
"2015-07-01T09:06:46.852Z"
the time string is UTC time ,not local time.

return java.util.Date type is more better.

And I  suggest add a method like:
influxDB.query(Query query,TimeZone timeZone)

**Comment by majst01** [comment]
From my understanding of the resulting json of a influxdb query the columns can container either dates, as you mentioned or something else, but it is always at least a String.
Therefore i created a Result Object which can consume all kinds of responses from any arbitrary query.
For the moment i think a result of a query can not be more specific, if i, or you create a more specific method like queryPoints i can imagine a more specific result object which returns the date in a date compatible type.

**Comment by thetcc** [comment]
Maybe you are right,
the time column in influxdb 0.8.x version,it seems to be the number of milliseconds  in my memory.
but in 0.9 version ,it return a UTC time string.
It looks more readable, but very inconvenient to use,
I must cast it to local time because my timezone is Asia/Shanghai

**Comment by majst01** [comment]
The discussion about this actually started in #46, i will close this ticket because it is not specific enough
