### ISSUE TITLE
Scientific notation for large double values

### ISSUE THREAD

**Issue by ivanscattergood** [influxdb/influxdb-java#54]
Hi, 

We have noticed a problem when writing Doubles to the influxdb. Over a certain size doubles will be formatted in scientific notation. We have worked around this by adding an extra if statement to handle doubles specifically in the concatenateFields method of the point class: 

    if (value instanceof String) {
	    String stringValue = (String) value;                                
	    sb.append("\"").append(FIELD_ESCAPER.escape(stringValue)).append("\"");
    } else if (value instanceof Double) {                             
            
        DecimalFormat df = new DecimalFormat("0",DecimalFormatSymbols.getInstance(Locale.ENGLISH));
          df.setMaximumFractionDigits(340); //340 = DecimalFormat.DOUBLE_FRACTION_DIGITS
            sb.append(df.format(value));
    } else {                           
           //Addition ends here.
             sb.append(value);
    }

**Comment by majst01** [comment]
Hi @ivanscattergood 

Thanks for pointing this out. I took a slightly different approach which also works for other Number instances as well. See the TicketTests.java which cases are covered.

**Comment by ivanscattergood** [comment]
Hi Stefan,
Thanks, for sorting this so quickly !

Ivan


---- Stefan Majer wrote ----


Hi @ivanscattergood<https://github.com/ivanscattergood>

Thanks for pointing this out. I took a slightly different approach which also works for other Number instances as well. See the TicketTests.java which cases are covered.

-

**Comment by majst01** [comment]
Hi Ivan,

can you please test and close this issue if your problem is resolved.

**Comment by ivanscattergood** [comment]
Of course, I won't get a chance till this evening


---- Stefan Majer wrote ----


Hi Ivan,

can you please test and close this issue if your problem is resolved.

-
