### ISSUE TITLE
do i have to close the connection?

### ISSUE THREAD

**Issue by kcrosswind** [influxdb/influxdb-java#56]
afer i use influxdb, 
InfluxDB influxDB = InfluxDBFactory.connect("http://localhost:8086", "admin", "admin");
how can i release resource?
or it is no need for

**Comment by majst01** [comment]
Hi @kcrosswind 

there is not need to release the connection.

Greetings
Stefan

**Comment by kcrosswind** [comment]
hi @majst01 
thank you for you help
