### ISSUE TITLE
Unable to set precision other than nanoseconds for a write

### ISSUE THREAD

**Issue by awstewar** [influxdb/influxdb-java#59]
The API has the precision hardcoded to nanoseconds which makes it impossible to pass in a point with a different precision.
https://github.com/influxdb/influxdb-java/blob/master/src/main/java/org/influxdb/impl/InfluxDBImpl.java#L160

**Comment by majst01** [comment]
No,
because in 
https://github.com/influxdb/influxdb-java/blob/master/src/main/java/org/influxdb/dto/Point.java#L283

The time set in a Point is calculated to nanoseconds from Points precision. 

If you still think its wrong, can you show me a failing test case ?
