### ISSUE TITLE
Release 1.6 does not exist

### ISSUE THREAD

**Issue by enric-sinh** [influxdb/influxdb-java#60]
The current README on master says:
`To connect to InfluxDB 0.8.x you need to use influxdb-java version 1.6.`

But I cannot find any release nor tag for 1.6.

Is this release missing or maybe it's a typo in the README?

**Comment by majst01** [comment]
Hi,

same reason why 2.0 is not on maven repo. I still try together with the influxdb guys to upload these artifact to mavencentral.

sorry for that and stay tuned.
Stefan

**Comment by jpbetz** [comment]
I've hit the same problem.  Would like to use 2.0, but is does not appear in maven central.

**Comment by enric-sinh** [comment]
In my case, I meant that I cannot find the `1.6` version as a Github release or tag of the repo.
That's why I thought that `1.6` was a typo that meant `1.5`.
