### ISSUE TITLE
Cannot insert String value, when using driver from scala

### ISSUE THREAD

**Issue by waxzce** [influxdb/influxdb-java#62]
Have an exception when inserting data with string value field
java.lang.RuntimeException: unable to parse 'check,fqdn=www.clevqsdfer-cloud.com error_name=java.net.UnknownHostException,status=0,working=false 1437936048997': invalid boolean

But working if I add quotes from myself, will try to fix

**Comment by waxzce** [comment]
Seems linked to Scala Types...

**Comment by majst01** [comment]
Can you show the whole code which demonstrates this including the full stack trace ? Otherwise for me its difficult to see whats happening.

**Comment by waxzce** [comment]
Are you familiar with scala ?

The point is simple: scala String type wrap all string in a scala program... So, this is the problem:
https://github.com/influxdb/influxdb-java/blob/master/src/main/java/org/influxdb/dto/Point.java#L266
because it's not an instance of java string... I found a workaround casting from scala string to java string.

Maybe the more simple way is to provide a scala wrapper to manage this kind of problem. What do you think about?

**Comment by majst01** [comment]
Hi @waxzce 

I dont now scala and how it works. So the only solution i see is that a scala guy like you write a wrapper which can solve your problem.

**Comment by waxzce** [comment]
I'm working on a project with influx and scala next week, will take time to write a wrapper and push it :-)
