### ISSUE TITLE
write method: java.lang.NullPointerException

### ISSUE THREAD

**Issue by karma243** [influxdb/influxdb-java#63]
Hi, I tried testing the sample code provided to understand the functionality of InfluxDB. I was able to connect to the Database and could perform query on existing database (which I created using CLI) but writing data is causing trouble.
1. When I try to write data in batch, using BatchPoints, I am getting NullPointerException.
```java
public class connector {

    public static void main(String[] args) {
        try {
            InfluxDB influxDB = InfluxDBFactory.connect("http://localhost:8086", "username", "password");
            String dbName = "testdatabase1";
            influxDB.createDatabase(dbName);

            BatchPoints batchPoints = BatchPoints
                    .database(dbName)
                    .tag("async", "true")
//                    .time(1,TimeUnit.SECONDS)
                    .retentionPolicy("default")
                    .consistency(InfluxDB.ConsistencyLevel.ALL)
                    .build();

            Point point1 = Point.measurement("cpu")
                    .time(System.currentTimeMillis(), TimeUnit.MILLISECONDS)
                    .field("idle", 90L).field("user", 9L)
                    .field("system", 1L)
                    .build();
            Point point2 = Point.measurement("disk")
                    .time(System.currentTimeMillis(), TimeUnit.MILLISECONDS)
                    .field("used", 80L)
                    .field("free", 1L)
                    .build();

            System.out.println("Ping time was: " + influxDB.ping().getResponseTime());
            batchPoints.point(point1);
            batchPoints.point(point2);
            influxDB.write(batchPoints);

            Query query = new Query("show series", dbName);
            influxDB.query(query);
//            influxDB.deleteDatabase(dbName);
        } catch(Exception e){
            e.printStackTrace();
        }

    }
}
```
I added .time in the batchpoint builder and was not getting NullPointer Exception. Now I could create the series but still could not write data in it.
The response I got was as following:
* 
Ping time was: 3
java.lang.NullPointerException
	at org.influxdb.impl.TimeUtil.toTimePrecision(TimeUtil.java:21)
	at org.influxdb.impl.InfluxDBImpl.write(InfluxDBImpl.java:155)
	at connector.main(connector.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)

Process finished with exit code 0 
*

2. When I try writing data after enabling the batch functionality, again the data was not getting written (this time even series was not being created).

**Comment by majst01** [comment]
Can you please specify which version (git sha1) you are using ?

**Comment by karma243** [comment]
I am using jitpack.io
```
 <repositories>
        <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>

    </repositories>

    <dependencies>

        <dependency>
            <groupId>com.github.influxdb</groupId>
            <artifactId>
                influxdb-java
            </artifactId>
            <version>influxdb-java-2.0</version>

        </dependency>
    </dependencies>
```

**Comment by majst01** [comment]
ok, this version is not the latest head from master, it is a arbitrary version weeks ago. 
The Bug you are seeing is already fixed in the latest head

**Comment by karma243** [comment]
Thank you @majst01 . It is working now.

**Comment by nikotincheg** [comment]
Hi, I'm using influx dependency in the same way (using jitpack.io) and have the same exception. Please explain how can I use latest version of influx-java lib with maven and when the fixed will be released? Thanks!

**Comment by gargde** [comment]
I am also facing the similar issue. Please let us know how it was solved.
