### ISSUE TITLE
ClassNotFoundException: for Strings

### ISSUE THREAD

**Issue by shilpisharma** [influxdb/influxdb-java#68]
Hi,

I built the project to use it to communicate with influxDB, but I am getting a ClassNotFoundException for Strings Class.

I am not sure what I'm missing. Can someone help.

I am running influx client from my local Windows system, to access InfluxDB installed at an Ubuntu server.

Shilpi

**Comment by majst01** [comment]
Strings comes from guava, do you hava guava in your classpath ?

**Comment by shilpisharma** [comment]
I added Guava 18 in classpath. Now it's giving me a new error:
Caused by: java.lang.ClassNotFoundException: retrofit.ErrorHandler

Is there another jar for this that I need to include/add in classpath?

**Comment by shilpisharma** [comment]
It finally worked. I imported few more jars. Thanks for your help.

**Comment by ItsRajesh4uguys** [comment]
@shilpisharma  what are all the few jars which you have added. I am also facing the same issue. Please help me.

**Comment by andrewdodd** [comment]
Is this in your project or in a checkout of influxdb-java?
Are you using maven?

**Comment by ItsRajesh4uguys** [comment]
I have fixed this now. Yes I have used Maven libs only. After adding the correct version of okhttp and okio it resolved. Thanks.
