### ISSUE TITLE
Escaping of equals character, '='.

### ISSUE THREAD

**Issue by emothershaw** [influxdb/influxdb-java#76]
Hi,

Recently when trying to write points with tags where the value is a string with '=' characters in it. The Influxdb java library "write" method throws an error. An example of this is

13:33:49.985 [OpenAccessApiClient-UnknownDevBuild-akka.actor.default-dispatcher-4] ERROR persistance.Engine - java.lang.RuntimeException: unable to parse 'metric,BU=Business\ Driven\ IT,Column\ name=args,Data\ View=processes,Gateway=Ed's\ gateway,Header\ Column=/opt/google/chrome/chrome\ --type=renderer\ --enable-pinch\ --enable-deferred-image-decoding\ --lang=en-GB\ --force-fieldtrials=AffiliationBasedMatching/Enabled/AudioProcessing48kHzSupport/Default/*AutofillEnabled/Default/CaptivePortalInterstitial/Disabled/*ChildAccountDetection/Disabled/ChromeDashboa...,Main\ Office=Epsom\ 1234,Managed\ Entity=ME01,Region=Surrey,Row\ name=all#002,Variable\ name=all#002\ -\ args Severity="UNDEFINED",Severity\ id=0,Type="Metric",value=-1.01234 1438778017000000000': missing tag value

Many thanks,

Ed

**Comment by caoli5288** [comment]
Can influxdb's native api support '=' character in tags?

**Comment by beckettsean** [comment]
Yes, the API has no problem with `=` in tags, provided the character is properly escaped with a backslash `\`.

**Comment by mnuessler** [comment]
Is this already fixed through PR #102?

**Comment by majst01** [comment]
Yes of course :-)
