### ISSUE TITLE
Creating InfluxDb using java code.

### ISSUE THREAD

**Issue by sims143** [influxdb/influxdb-java#81]
I want to manage influxDb (Creating Database, Writing Data, Retrieving data) through java coding. I came across InfluxDb-Java but I cannot figure out how to use it. Which library is need to be imported into my java file for implementing InfluxDb. It would be great if someone can share sample code of creating database and writing data to that database.

PS: I am working on maven project.

**Comment by sims143** [comment]
Posting more details:
OS : Ubuntu 15.4
Code which I using to execute:
public class Influxdb
	{
		InfluxDB influxDB = InfluxDBFactory.connect("http://127.0.0.1:8086", "root", "root");
		String dbName = "aTimeSeries";
		influxDB.createDatabase(dbName);

	}

Output which I am expecting:
-> In the Web Admin Interface of Influxdb,  "aTimeSeries" database name has to be appeared.
Web Admin Interface works on "localhost:8083"

**Comment by majst01** [comment]
Did you try to insert a single point and see what happens ?

**Comment by sims143** [comment]
I have configured it successfully. Thanks! 

You can close the issue.
