### ISSUE TITLE
Error while importing Point class in Influxdb-java v1.5

### ISSUE THREAD

**Issue by sims143** [influxdb/influxdb-java#82]
I am using Influxdb-java 1.5 version. To built a measurement in a database we need to use "Point" class present in "org.influxdb.dto.Point". I am trying to import it with "import org.influxdb.dto.Point;" but its not getting imported and arising the below error

[23,24] cannot find symbol
  symbol:   class Point
  location: package org.influxdb.dto

Can anyone help me with that??

**Comment by majst01** [comment]
Hi @sims143 

You need to use influxdb-java 2.0 build from git, it is still not available on maven repo. So clone it and compile it with maven clean install -Dmaven.test.skip.

**Comment by sims143** [comment]
I have configured it successfully. Thanks! 

You can close the issue.
