### ISSUE TITLE
Change to line protocol in 0.9.3

### ISSUE THREAD

**Issue by ivanscattergood** [influxdb/influxdb-java#83]
Hi, 
It looks like there is a change to the line protocol in version 0.9.3, do you plan to implement this functionality?

>Integers are numeric values that do not include a decimal and are followed by a trailing i when inserted >(e.g. 1i, 345i, 2015i, -10i). Note that all values must have a trailing i. If they do not they will be written as >floats.

**Comment by mnuessler** [comment]
Is this already implemented through PR #115 or is there still work to be done?

**Comment by majst01** [comment]
Hi,

#115 was merged 2 weeks ago, so if you use the master branch you are fine.
