### ISSUE TITLE
cannot build

### ISSUE THREAD

**Issue by tvmanikandan** [influxdb/influxdb-java#96]
Hello,
I tried mvn clean install with docker versions 1.3.0 and 2.1.1. In both cases write operation fails with below error.

Failed tests:   testWrite(org.influxdb.InfluxDBTest): {"error":"invalid character 'c' looking for beginning of value"}(..)

Could you please help?

-Mani

**Comment by majst01** [comment]
There is no docker version 2.1.1 ? to what kind of software are you referencing ?
