### ISSUE TITLE
Memory consumption issue: Incorrect supporting of field values with Integer type

### ISSUE THREAD

**Issue by nikotincheg** [influxdb/influxdb-java#98]
Please add Integer type supporting. At this moment all number values saved as float.
For example integer value = 5 will be formatted to 5.0 and saved in InfluxDB as float.
To save as integer need to use following format: 5i

Example: 
test,code=516d5ae3-856e-411f-80d4-ead7bc2ca624 count=10i 1443457366432000000

**Comment by majst01** [comment]
This is a duplicate of #83
